/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agendacontactos;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class InterfazMostrar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMostrar
     */
    public InterfazMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Correo", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cerrar.setText("cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Familia", "Trabajo", "Amigos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cerrar)
                .addGap(94, 94, 94)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cerrar)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        Menu instancia = new Menu();
        dispose();
        instancia.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GetUsers();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMostrar().setVisible(true);
            }
        });
    }

    private void GetUsers() {
        ListaEnlazadaSimple listaAmigo = InterfazAgregar.getListaAmigos();
        ListaEnlazadaSimple listaTrabajo = InterfazAgregar.getListaTrabajo();
        ListaEnlazadaSimple listaFamilia = InterfazAgregar.getListaFamilia();

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        limpiarTabla(jTable1);

        int count = 0;
        listaAmigo.mostrarDatosLista();
        Object[] list = new Object[4];
        NodoLista prueba;

        String seleccion = (String) jComboBox1.getSelectedItem();

        if (seleccion.equals("Amigos")) {
            prueba = listaAmigo.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
        } else if (seleccion.equals("Familia")) {

            prueba = listaFamilia.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
        } else if (seleccion.equals("Trabajo")) {
            prueba = listaTrabajo.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
        }else if(seleccion.equals("Todos")){
            prueba = listaFamilia.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
            
            prueba = listaAmigo.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
            
            prueba = listaTrabajo.primero;
            while (prueba != null) {
                list[0] = prueba.datoNombre;
                list[1] = prueba.datoTelefono;
                list[2] = prueba.datoCorreo;
                list[3] = prueba.datoCategoria;
                modelo.addRow(list);
                prueba = prueba.siguiente;
            }
        }        
        jTable1.setModel(modelo);
    }
    
    public static void limpiarTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        tabla.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
